# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=<your_db_user>
      - DB_PASSWORD=<your_db_password>
      - DB_NAME=<your_db_name>
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=<your_db_user>
      - POSTGRES_PASSWORD=<your_db_password>
      - POSTGRES_DB=<your_db_name>
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: